config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'terms'   => 'static_pages#terms'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :cards,               only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :subscriptions
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cards, dependent: :destroy
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
                        
  has_secure_password
  ## Must have one integer, one letter, between 8-40 characters, allows special char
  VALID_PASS_REGEX = /\A(?=.*\d)(?=.*([a-z]|[A-Z]))([\x20-\x7E]){8,40}\z/
  validates :password,                      length: { minimum: 8 }, allow_blank: true,
                                            format: { with: VALID_PASS_REGEX, 
                                                      message: "fails requirements"}
  validates :address_line1, presence: true, length: { maximum: 100 }
  validates :address_line2,                 length: { maximum: 100 }
  validates :city, presence: true,          length: { maximum: 100 }
  validates :state, presence: true,         length: { maximum: 100 }
  validates :zip, presence: true,           length: { maximum: 20 }
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  
  private 
    
    def downcase_email
      self.email = email.downcase
    end
    
    # Creates and assigns the activation token and digest
    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update]
  before_action :admin_user,     only: [:destroy, :index]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @card = current_user.cards.build if logged_in?
    @cards = @user.cards
  end
  
  def new
    @user = User.new 
  end
  
  def create 
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  ## This is used in the index by admin to destroy ANOTHER user
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  
  ## This is to destroy self
  ## Does not currently work
=begin 
  def destroy_self
    begin
      if destroy_stripe_self
        User.find_by_email(@current_user.email).destroy
        flash[:success] = "Your account has been successfully deleted."
        redirect_to root_url
      else 
        flash[:danger] = "Something went wrong, please try again."
        redirect_to request.referrer
      end
      
      rescue => e 
        flash[:danger] = e.message
    end
  end
=end
  
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, 
      :address_line1, :address_line2, :city, :state, :zip)
    end
    
    # Before filters

    
    # Confirms the correct user
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # Confirms an admin user
    def admin_user 
      redirect_to(root_url) unless current_user.admin?
    end
  
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>


<div class="row" id="user_edit_form">
  <div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Password: (Length: 8-40 characters. At least 1 letter and 1 number.)" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label :address_line1, "Address Line 1" %>
      <%= f.text_field :address_line1, class: 'form-control' %>
      
      <%= f.label :address_line2, "Address Line 2" %>
      <%= f.text_field :address_line2, class: 'form-control' %>
      
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
      
      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>
      
      <%= f.label :zip %>
      <%= f.text_field :zip, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>

<div class="row" id="signup_form">
  <div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :password, "Password: (Length: 8-40 characters. At least 1 letter and 1 number.)" %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label :address_line1, "Address Line 1" %>
      <%= f.text_field :address_line1, class: 'form-control' %>
      
      <%= f.label :address_line2, "Address Line 2" %>
      <%= f.text_field :address_line2, class: 'form-control' %>
      
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
      
      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>
      
      <%= f.label :zip %>
      <%= f.text_field :zip, class: 'form-control' %>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
      <small>Note: By creating your account you are acknowledging 
      that you have read and accept our <%= link_to "Terms of Use and Privacy Policy",   terms_path %>.</small>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  
  <div class="container container-fluid">
    <div class="row my-card-container">
        <% if @user.stripe_customer_token.nil? %>
          <div class="col-sm-8 col-sm-offset-2 center">
            <h3>Hi <%= @user.name %>, </h3>
            <p>Thanks for signing up!  Take a look at our designs and when you are ready to pick your 
            cards, use the link below to enter your payment info.  We'll only ask 
            you to enter it this once, so managing your card preferences will be nice 
            and painless from here on out.  <strong>You will not be charged for anything 
            until we send you a card.</strong></p>
            <hr class="divider-blue">
            <h3>Enter your payment info to get started</h3>
            <%= link_to "Add Credit Card", new_subscription_path, class: "btn btn-primary btn-add-card" %>
          </div>
        <% else %>
          <div class="col-md-4">

            <div class="col-sm-8 col-sm-offset-2 center">
              <div class="row">
                <div class="col-sm-12">
                  <%= render 'shared/card_form' %>
                  Please allow 2-3 weeks for initial card delivery.
                </div>
                <div class="col-sm-12">
                  <hr class="divider-blue">
                  
                  <%= link_to "Update Credit Card", edit_subscription_path, class: "btn btn-primary btn-update-card" %>
                </div>
                
                <div class="col-sm-12">
                  <hr class="divider-blue">
                  <h4>Important Dates</h4>
                  <ul class="list-group">
                    <li class="list-group-item">Valentines: Feb 14</li>
                    <li class="list-group-item">Mothers(US) 2016: May 8</li>
                    <li class="list-group-item">Fathers(US) 2016: June 19</li>
                    <li class="list-group-item">Christmas: Dec 25</li>
                  </ul>
                </div>
                
              </div>
            </div>
            </div>
          <% end %>
      
        <div class="col-md-8"> 
          <div class="row">
            <% if @user.cards.any? %>
            <div class="col-sm-12">
              <h2>
                <%= @user.name %>'s Cards
              </h2>
              <h3 class="center">You are currently signed up to receive <%= @user.cards.count  %> cards annually.</h3>
            </div>
            <div class="col-sm-8 col-sm-offset-2">
              <div class="row">
                <%= render @cards %>
              </div>
              <div class="row card-note">
                Note: Each card will be delivered annually in advance of the date listed above.
              </div>
            </div>
            
            <% else %>
              <% if @user.stripe_customer_token %>
                <div class="col-sm-8 col-sm-offset-2">
                  <h2 class="center">Hi <%= @user.name %>, </h2>
                  <p>Your account is set up!</p> 
                  
                  <p>Check out 
                  the designs below and use the form on this page to add as many cards as you'd like.</p>
                  
                  <p>Each card costs 5 dollars per year.  Just enter your important date 
                  and we'll mail it out in advance.</p>
                  
                  <p>You can update your payment info any time  
                  by clicking the "Update Credit Card" button on this page.  If 
                  you need to update your address or password, 
                  choose "My Info" from the drop-down up in the navigation bar.</p>
                  
                  <p>Have questions or feedback? Don't hesitate to reach out to 
                  colby@earlycard.com or on Twitter @myearlycard.  Thanks for signing up, we're happy 
                  you're here.</p>
                
  
                </div>
              <% end %>
            
            <% end %>
          </div>
        </div>
    </div>

  
  <hr class="divider-blue">
  <div class="container container-fluid">
    <h2>Card Designs</h2>
    <p class="center">Each design below prints on a 5x7 linen paper stock greeting card.</p>
    <div class="row">
        <div class="col-sm-6 col-md-4 thumbnail">
  
          <div class="caption card-caption">
            <h3>Holiday</h3>
          </div>
          
          <%= image_tag("holidays240x336.png", class: "card-thumb", alt: "Holiday Card") %>
          
        </div>
        
        <div class="col-sm-6 col-md-4 thumbnail">
  
          <div class="caption card-caption">
            <h3>Anniversary</h3>
          </div>
          <%= image_tag("anniversary240x336.png", class: "card-thumb", alt: "Anniversary Card") %>
        </div>
        
        
        <div class="col-sm-6 col-md-4 thumbnail">
  
          <div class="caption card-caption">
            <h3>Birthday</h3>
          </div>
          <%= image_tag("birthday240x336.png", class: "card-thumb", alt: "Birthday Card") %>
        </div>
        
        
        <div class="col-sm-6 col-md-4 thumbnail">
          <div class="caption card-caption">
            <h3>Father's Day</h3>
          </div>
          <%= image_tag("fathers240x336.png", class: "card-thumb", alt: "Father's Day Card") %>
        </div>
        
        
        <div class="col-sm-6 col-md-4 thumbnail">
          <div class="caption card-caption">
            <h3>Mother's Day</h3>
          </div>
          <%= image_tag("mothers240x336.png", class: "card-thumb", alt: "Mother's Day Card") %>
        </div>
        
        
        <div class="col-sm-6 col-md-4 thumbnail">
          <div class="caption card-caption">
            <h3>Valentine's Day</h3>
          </div>
          <%= image_tag("valentines240x336.png", class: "card-thumb", alt: "Valentine's Day Card") %>
        </div>
    </div>
  
</div>