config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'terms'   => 'static_pages#terms'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :cards,               only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :subscriptions
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  
  def new
    @user = current_user
    render 'subscriptions/new'
  end
  
  def create
    
    begin
      @user = User.find_by_email(params[:stripeEmail])
      
      customer = Stripe::Customer.create(
        :email => @user.email,
        :card  => params[:stripeToken]
      )
      
      # Save customer ID to user
      @user.stripe_customer_token = customer.id
      @user.save
      
      flash[:success] = "Thanks for the info. Now go ahead and add some cards!"
      redirect_to @user
      
      rescue Stripe::StripeError => e
        flash[:danger] = e.message
        redirect_to request.referrer
      
      rescue => e 
        flash[:danger] = e.message
        redirect_to request.referrer
    end
  end
  
  def edit
    @user = current_user
    render 'subscriptions/edit'
  end
  
  def update
    
    begin
      @user = User.find_by_email(params[:stripeEmail])
      
      customer = Stripe::Customer.retrieve(@user.stripe_customer_token)
      customer.source = params[:stripeToken]
      customer.save
      
      flash[:success] = "Thanks for the info. Now go ahead and add some cards!"
      redirect_to @user
      
      rescue Stripe::StripeError => e
        flash[:danger] = e.message
        redirect_to request.referrer
      
      rescue => e 
        flash[:danger] = e.message
        redirect_to request.referrer
    end
    
  end
  
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/create.html.erb
<h2>Thanks for signing up! Now add some cards!</h2>

app/views/subscriptions/edit.html.erb
<div class="center">
  <div class="jumbotron">
  <%= image_tag("logo200.png", alt: "earlycard logo") %>
  </div>

  <%= form_tag({:action => 'update'}, :method => :put, :id =>"sub_form") do %>
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <input type=hidden id="stripe_token" name=stripeToken />
    <input type=hidden id="stripe_email" name=stripeEmail />
    <button id="customButton" class="btn btn-primary action-btn">Update Card</button>
    
    <script>
    
    $( document ).ready(function() {
      
      var user_email = document.getElementById("user_email").textContent;
      
      
    
      $('#customButton').on('click', function(e) {
        
        var handler = StripeCheckout.configure({
          key: '<%= Rails.application.secrets.stripe_publishable_key %>',
          panelLabel: 'Save',
          color: 'black',
          locale: 'auto',
          token: function(token, args) {
                document.getElementById("stripe_token").value = token.id;                              
                document.getElementById("stripe_email").value = token.email;
                document.getElementById("sub_form").submit();
          }
        });
          
        // Open Checkout with further options
        handler.open({
          name: 'www.earlycard.com',
          description: 'Update Credit Card',

          email: user_email
        });
        e.preventDefault();
      });
    
      // Close Checkout on page navigation
      $(window).on('popstate', function() {
        handler.close();
      });
    
    });

    </script>
    
  <% end %>
  
  <br/>
  <p><%= @user.name %></p>
  <p id="user_email"><%= @user.email %></p>
  <p>Note: Your card will not be charged at this time.</p>
  
</div>

app/views/subscriptions/new.html.erb
<div class="center">
  <div class="jumbotron">
    <%= image_tag("logo200.png", alt: "earlycard logo") %>
  </div>
  
  <%= form_tag subscriptions_path, id: "sub_form" do %>
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <input type=hidden id="stripe_token" name=stripeToken />
    <input type=hidden id="stripe_email" name=stripeEmail />
    <button id="customButton"class="btn btn-primary action-btn">ADD CREDIT CARD</button>
    
    <script>
    
    $( document ).ready(function() {
      
      var user_email = document.getElementById("user_email").textContent;
      
    
      $('#customButton').on('click', function(e) {
        
        var handler = StripeCheckout.configure({
          key: '<%= Rails.application.secrets.stripe_publishable_key %>',
          panelLabel: 'Save',
          locale: 'auto',
          token: function(token, args) {
                document.getElementById("stripe_token").value = token.id;                              
                document.getElementById("stripe_email").value = token.email;
                document.getElementById("sub_form").submit();
          }
        });
        
        // Open Checkout with further options
        handler.open({
          name: 'www.earlycard.com',
          description: 'Credit Card Info',
          email: user_email
        });
        e.preventDefault();
      });
    
      // Close Checkout on page navigation
      $(window).on('popstate', function() {
        handler.close();
      });
      
    });
    </script>
  <% end %>
  
  <br/>
  <p><%= @user.name %></p>
  <p id="user_email"><%= @user.email %></p>
  <p>Note: Your card will not be charged at this time.</p>
  
</div>

app/views/subscriptions/update.html.erb
<h2>Info Updated Successfully</h2>