config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'terms'   => 'static_pages#terms'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :cards,               only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :subscriptions
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p> &#169; 2015 - Earlycard, LLC</p>
   <p><%= link_to image_tag("twitter.png", alt: "twitter"), "https://twitter.com/myearlycard" %></p>
   <p><%= link_to "About | FAQ",   about_path %></p>
   <p><%= link_to "Terms of Use | Privacy Policy",   terms_path %></p>
</footer>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
    ga('create', 'UA-54221306-4', 'auto');
    ga('send', 'pageview');
  
  </script>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "earlycard", root_path, id: "earlycard", class: "navbar-brand" %>
    </div>
    <div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Cards", current_user %></li>
              <li><%= link_to "My Info", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign Up", signup_path, class: "btn btn-signup" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <%= favicon_link_tag 'favicon.ico' %>
    
    <!-- Raleway Google font -->
    <link href='//fonts.googleapis.com/css?family=Raleway:400,500,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    
    <!-- Satisfy Google font -->
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/google_analytics' %>
  </head>
  <body>
    <div class="container-body">
    <%= render 'layouts/header' %>
    
      <div class="content-body">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
      
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>